### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by shimwell** [mateczentye/example_python_package_mate#1]
- [x] add test for my_name function
- [x] make github action to  run pytest automatically
- [x] register account with pypi
- [ ] make github action to upload to pypi
- [ ] make a development branch
- [ ] add feature from development branch to main branch
